### ISSUE TITLE
Having issues compiling the code

### ISSUE THREAD

**Issue by antoniomtz** [yunus-temurlenk/opencv-barcodedetector-class-test#1]
Hello, I'm not using the IDE you showed on your video, and I'm wondering how can I compile this code in the command line. 
I have installed openCV 4.8.0.
After I ran the binary, I get the following error:

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.8.0) $HOME/opencv/modules/objdetect/src/barcode.cpp:348: error: (-215:Assertion failed) utils::fs::exists(prototxt_path) in function 'BarcodeDetector'
```

Thanks

**Comment by antoniomtz** [comment]
I was missing the prototxt files

**Comment by yunus-temurlenk** [comment]
> Hello, I'm not using the IDE you showed on your video, and I'm wondering how can I compile this code in the command line. I have installed openCV 4.8.0. After I ran the binary, I get the following error:
> 
> ```
> terminate called after throwing an instance of 'cv::Exception'
>   what():  OpenCV(4.8.0) $HOME/opencv/modules/objdetect/src/barcode.cpp:348: error: (-215:Assertion failed) utils::fs::exists(prototxt_path) in function 'BarcodeDetector'
> ```
> 
> Thanks

the compiling command without using anide is just this:

`g++ -std=c++14 main.cpp `pkg-config --libs --cflags opencv4` -o output`
